services:
  - type: web
    name: mf-frontend
    env: static
    buildCommand: |
      npm install --legacy-peer-deps --verbose &&
      npx react-scripts build
    staticPublishPath: ./build
    envVars:
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff