services:
  - type: web
    name: mf-frontend
    env: static
    buildCommand: |
      export NODE_OPTIONS="--max_old_space_size=4096" &&
      npm install --legacy-peer-deps &&
      node --max_old_space_size=4096 node_modules/.bin/react-scripts build
    staticPublishPath: ./build
    envVars:
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: true
      - key: NODE_OPTIONS
        value: "--max_old_space_size=4096"
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff