services:
  - type: web
    name: mf-frontend
    env: static
    buildCommand: npm ci && npm run build:production
    staticPublishPath: ./build
    envVars:
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff